[project]
name = "typing-conformance"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "mypy",
    "pyrefly",
    "pyright",
    "tomli",
    "tomlkit",
    "zuban",
]

[tool.uv]
package = false
